"""create association table Articles with Tags

Revision ID: 198c7fd1eb46
Revises: 3fd0d7bc25ea
Create Date: 2021-01-12 07:50:46.964129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '198c7fd1eb46'
down_revision = '3fd0d7bc25ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_tag_association',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_tag_association')
    # ### end Alembic commands ###
